version: "3.9"

services:
  api:
    image: ${REGISTRY:-ghcr.io}/${REGISTRY_NAMESPACE:-alabuga}/alabuga-api:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=3001
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3001/health || curl -fsS http://localhost:3001/api/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # ==== УНИКАЛЬНЫЕ ИМЕНА ====
      - "traefik.http.routers.${STACK}-api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.${STACK}-api.entrypoints=web"
      - "traefik.http.routers.${STACK}-api.service=${STACK}-api"
      - "traefik.http.services.${STACK}-api.loadbalancer.server.port=3001"

      # Если в приложении /health без /api — раскомментируй две строки ниже:
      # - "traefik.http.middlewares.${STACK}-api-strip.stripprefix.prefixes=/api"
      # - "traefik.http.routers.${STACK}-api.middlewares=${STACK}-api-strip@docker"

    restart: unless-stopped

  web:
    image: ${REGISTRY:-ghcr.io}/${REGISTRY_NAMESPACE:-alabuga}/alabuga-web:${TAG:-latest}
    depends_on:
      - api
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # ==== УНИКАЛЬНЫЕ ИМЕНА ====
      - "traefik.http.routers.${STACK}-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${STACK}-web.entrypoints=web"
      - "traefik.http.routers.${STACK}-web.service=${STACK}-web"
      - "traefik.http.services.${STACK}-web.loadbalancer.server.port=80"

    restart: unless-stopped

networks:
  default:
    name: proxy
    external: true
