services:
  api:
    image: ${REGISTRY:-ghcr.io}/${REGISTRY_NAMESPACE:-alabuga}/alabuga-api:${TAG:-latest}
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
  web:
    image: ${REGISTRY:-ghcr.io}/${REGISTRY_NAMESPACE:-alabuga}/alabuga-web:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped