services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
