name: Deploy

on:
  push:
    branches:
      - master
      - feature/update-main-page-design

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build front-end
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  build-images:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Prepare tags
        id: tags
        run: |
          BRANCH="${GITHUB_REF_NAME//\//-}"
          echo "branch_tag=$BRANCH" >> "$GITHUB_OUTPUT"
          if [ "$BRANCH" = "master" ]; then
            echo "latest_tag=latest" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=" >> "$GITHUB_OUTPUT"
          fi

      - name: Build & push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/api.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/alabuga-api:${{ steps.tags.outputs.branch_tag }}
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/alabuga-api:${{ steps.tags.outputs.latest_tag }}

      - name: Build & push WEB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/alabuga-web:${{ steps.tags.outputs.branch_tag }}
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/alabuga-web:${{ steps.tags.outputs.latest_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, build-images]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feature/update-main-page-design'
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            set -e
            BRANCH="${GITHUB_REF_NAME//\//-}"
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch --all
            git checkout "$BRANCH" || git checkout -b "$BRANCH" "origin/$BRANCH"
            git reset --hard "origin/$BRANCH"
            export REGISTRY=${{ env.REGISTRY }}
            export REGISTRY_NAMESPACE=${{ env.REGISTRY_NAMESPACE }}
            export TAG="$BRANCH"
            docker compose down || true
            docker compose pull
            docker compose up -d
            docker system prune -f