name: Build & Deploy

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/Tag/Commit to deploy"
        required: true
        default: master
      domain:
        description: "Dev Domain"
        required: true
        default: dev.nvote.ru
      stack:
        description: "Stack name (project) e.g. prod, dev-feature"
        required: true
        default: dev

concurrency:
  group: deploy-${{ github.event_name }}-${{ github.ref || inputs.ref }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  # ---------- BUILD (общий для auto и manual) ----------
  build-and-push:
    name: Build & Push ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: api
            context: .
            file: docker/api.Dockerfile
            image_name: alabuga-api
          - service: web
            context: .
            file: Dockerfile
            image_name: alabuga-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Логинимся в GHCR от лица Actions (никаких персональных токенов не нужно)
      - name: Login to GHCR (via GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Нормализуем регистр namespace (владелец репо) → lower-case
      - name: Normalize owner/namespace
        id: norm
        run: |
          echo "NS_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "REG_LC=$(echo '${{ env.REGISTRY }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Compute tags
        id: t
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BRANCH="${{ inputs.ref }}"
          else
            BRANCH="${GITHUB_REF_NAME}"
          fi
          if [ "$BRANCH" = "master" ]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            SAFE=$(echo "$BRANCH" | tr '/_' '--')
            echo "TAG=dev-${SAFE}" >> $GITHUB_OUTPUT
          fi
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: |
            ${{ steps.norm.outputs.REG_LC }}/${{ steps.norm.outputs.NS_LC }}/${{ matrix.image_name }}:${{ steps.t.outputs.TAG }}
            ${{ steps.norm.outputs.REG_LC }}/${{ steps.norm.outputs.NS_LC }}/${{ matrix.image_name }}:${{ steps.t.outputs.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ---------- AUTO PROD DEPLOY (master push) ----------
  deploy-prod-auto:
    if: github.event_name == 'push' && github.ref_name == 'master'
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (compose)
        uses: actions/checkout@v4

      # Нормализуем namespace и прокинем в env деплоя
      - name: Normalize owner/namespace
        id: norm
        run: |
          echo "NS_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "REG_LC=$(echo '${{ env.REGISTRY }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "${{ secrets.DEPLOY_PATH }}/prod"

      - name: Deploy prod
        uses: appleboy/ssh-action@v1.0.3
        env:
          REGISTRY: ${{ steps.norm.outputs.REG_LC }}
          REGISTRY_NAMESPACE: ${{ steps.norm.outputs.NS_LC }}
          TAG: latest
          STACK: prod
          DOMAIN: ${{ vars.PROD_DOMAIN }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_PATH }}/prod
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REGISTRY,REGISTRY_NAMESPACE,TAG,STACK,DOMAIN,DEPLOY_DIR,REGISTRY_USER,REGISTRY_TOKEN
          script: |
            set -euo pipefail
            mkdir -p "$DEPLOY_DIR"
            cd "$DEPLOY_DIR"
            cat > .env <<EOF
            REGISTRY=${REGISTRY}
            REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}
            TAG=${TAG}
            DOMAIN=${DOMAIN}
            STACK=${STACK}
            EOF
            echo "${REGISTRY_TOKEN}" | docker login "${REGISTRY}" -u "${REGISTRY_USER}" --password-stdin
            docker compose -p "${STACK}" pull
            docker compose -p "${STACK}" up -d --remove-orphans
            docker image prune -f || true

  # ---------- MANUAL DEPLOY (любой домен/ветка/стек) ----------
  deploy-manual:
    if: github.event_name == 'workflow_dispatch'
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (compose)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Normalize owner/namespace
        id: norm
        run: |
          echo "NS_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "REG_LC=$(echo '${{ env.REGISTRY }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "${{ secrets.DEPLOY_PATH }}/${{ inputs.stack }}"

      - name: Deploy manual stack
        uses: appleboy/ssh-action@v1.0.3
        env:
          REGISTRY: ${{ steps.norm.outputs.REG_LC }}
          REGISTRY_NAMESPACE: ${{ steps.norm.outputs.NS_LC }}
          BRANCH: ${{ inputs.ref }}
          STACK: ${{ inputs.stack }}
          DOMAIN: ${{ inputs.domain }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_PATH }}/${{ inputs.stack }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REGISTRY,REGISTRY_NAMESPACE,BRANCH,STACK,DOMAIN,DEPLOY_DIR,REGISTRY_USER,REGISTRY_TOKEN
          script: |
            set -euo pipefail
            if [ "$BRANCH" = "master" ]; then TAG=latest; else TAG="dev-$(echo "$BRANCH" | tr '/_' '--')"; fi
            mkdir -p "$DEPLOY_DIR"
            cd "$DEPLOY_DIR"
            cat > .env <<EOF
            REGISTRY=${REGISTRY}
            REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}
            TAG=${TAG}
            DOMAIN=${DOMAIN}
            STACK=${STACK}
            EOF
            echo "${REGISTRY_TOKEN}" | docker login "${REGISTRY}" -u "${REGISTRY_USER}" --password-stdin
            docker compose -p "${STACK}" pull
            docker compose -p "${STACK}" up -d --remove-orphans
            docker image prune -f || true
